# Generated by Django 4.0.3 on 2022-03-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_alter_user_registerdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AlterField(
            model_name='app',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='app',
            name='EndDate',
            field=models.DateTimeField(auto_now_add=True, db_column='EndDate'),
        ),
    ]
