# Generated by Django 4.0.3 on 2022-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_delete_subscriptionplan_alter_app_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='SubscriptionDate',
            field=models.DateTimeField(db_column='SubscriptionDate', default=None),
        ),
        migrations.AlterField(
            model_name='app',
            name='EndDate',
            field=models.DateTimeField(db_column='EndDate', default=None),
        ),
    ]
