# Generated by Django 4.0.3 on 2022-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_app_subscriptiondate_alter_app_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='CreatedDate',
            field=models.DateTimeField(db_column='CreatedDate'),
        ),
    ]
