# Generated by Django 4.0.3 on 2022-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_alter_app_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RegisterDate',
            field=models.DateTimeField(db_column='RegisterDate'),
        ),
    ]
