# Generated by Django 4.0.3 on 2022-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_alter_user_registerdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='UpdatedDate',
            field=models.DateTimeField(db_column='UpdatedDate', default=None),
        ),
    ]
